[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NEXT_RUNTIME_VERSION = "4.0.0"

[dev]
  command = "npm run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    includeFiles = ["node_modules/next", "node_modules/styled-jsx"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[functions]
  directory = ".netlify/functions"